
import { NextRequest, NextResponse } from "next/server"
import { Resend } from "resend"
import { supabase } from "@/src/lib/supabase"

const resend = new Resend(process.env.RESEND_API_KEY)

// Simple in-memory rate limit
// One submission per IP per 60 seconds
const rateLimitMap = new Map<string, number>()

function isRateLimited(ip: string): boolean {
  const now = Date.now()
  const last = rateLimitMap.get(ip)
  if (last && now - last < 60_000) return true
  rateLimitMap.set(ip, now)
  return false
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json()

    const {
      email,
      company,
      role,
      teamSize,
      totalMonthlySavings,
      highSavings,
      honeypot,
      auditId,
    } = body

    // Honeypot check — silently reject bots
    if (honeypot) {
      return NextResponse.json({ ok: true })
    }

    // Basic email validation
    if (!email || !email.includes("@")) {
      return NextResponse.json(
        { error: "Valid email required" },
        { status: 400 }
      )
    }

    // Rate limit by IP
    const ip =
      req.headers.get("x-forwarded-for")?.split(",")[0] ?? "unknown"
    if (isRateLimited(ip)) {
      return NextResponse.json(
        { error: "Too many requests" },
        { status: 429 }
      )
    }

    // Save to Supabase
    const { error: dbError } = await supabase.from("leads").insert({
      audit_id: auditId ?? null,
      email,
      company: company ?? null,
      role: role ?? null,
      team_size: teamSize ?? null,
      total_monthly_savings: totalMonthlySavings ?? 0,
      high_savings: highSavings ?? false,
    })

    if (dbError) {
      console.error("Lead insert error:", dbError)
    }

    // Send confirmation email via Resend
    try {
      await resend.emails.send({
        from: "SpendLens <onboarding@resend.dev>",
        to: email,
        subject: highSavings
          ? "Your AI spend audit — Credex will be in touch"
          : "Your AI spend audit is ready",
        html: `
          <div style="font-family: monospace; max-width: 520px; margin: 0 auto; padding: 32px; background: #0c0c0e; color: #d0d0d8;">
            
            <p style="color: #00ff88; font-size: 12px; letter-spacing: 0.1em; margin-bottom: 24px;">
              SPENDLENS · AI SPEND AUDIT
            </p>

            <h1 style="font-size: 20px; font-weight: bold; margin-bottom: 16px; color: #f0f0f2;">
              Your audit report
            </h1>

            <p style="font-size: 14px; color: #6a6a7f; margin-bottom: 24px; line-height: 1.6;">
              ${
                totalMonthlySavings > 0
                  ? `We identified potential savings of <span style="color: #00ff88; font-weight: bold;">$${totalMonthlySavings}/month ($${totalMonthlySavings * 12}/year)</span> in your AI tool stack.`
                  : `Your AI tool stack appears well-optimised for your current usage profile. No significant savings opportunities were found.`
              }
            </p>

            ${
              highSavings
                ? `
              <div style="border: 1px solid rgba(0,255,136,0.2); padding: 16px; margin-bottom: 24px; background: rgba(0,255,136,0.04);">
                <p style="font-size: 13px; color: #d0d0d8; margin-bottom: 8px; font-weight: bold;">
                  Credex can help you capture more of this saving
                </p>
                <p style="font-size: 12px; color: #6a6a7f; margin-bottom: 12px; line-height: 1.6;">
                  Your savings profile qualifies for discounted AI infrastructure credits through Credex. A member of the Credex team will reach out within 2 working days to discuss how discounted credits could reduce your bill further.
                </p>
                <a href="https://credex.rocks" style="font-size: 12px; color: #00ff88; text-decoration: none;">
                  Book a consultation → credex.rocks
                </a>
              </div>
            `
                : `
              <div style="border: 1px solid #1c1c1f; padding: 16px; margin-bottom: 24px;">
                <p style="font-size: 12px; color: #6a6a7f; line-height: 1.6;">
                  We will notify you when pricing changes or new alternatives apply to your stack. AI tool pricing changes frequently — we check weekly.
                </p>
              </div>
            `
            }

            <p style="font-size: 12px; color: #4a4a5f; margin-bottom: 8px; line-height: 1.6;">
              This audit was generated by SpendLens — a free AI spend audit tool built by Credex. Every recommendation is based on verified vendor pricing and your specific team profile.
            </p>

            <p style="font-size: 11px; color: #2a2a3f; margin-top: 24px; padding-top: 16px; border-top: 1px solid #1c1c1f;">
              SpendLens is a free tool by Credex · 
              <a href="https://credex.rocks" style="color: #2a2a3f;">credex.rocks</a>
            </p>

          </div>
        `,
      })
    } catch (emailErr) {
      console.error("Resend error:", emailErr)
      // Never fail the request if email fails
      // Lead is already saved to Supabase
    }

    return NextResponse.json({ ok: true })
  } catch (err) {
    console.error("Leads route error:", err)
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 }
    )
  }
}